name: POI API CI-CD

on:
  push:
    paths: ['apis/poi/**', '.github/workflows/dotnet-core.yml']
  pull_request:
    branches: [ master ]
    
defaults:
  run:    
    working-directory: apis/poi/
    
jobs:
  job1:
    name: CI - Build and Test
    runs-on: ubuntu-latest

    steps:
    - run: |
        Status=$(curl -s 'https://openhackbxb3pxs9userjava.azurewebsites.net/api/healthcheck/user-java')
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Install dependencies
      run: dotnet restore
    - name: Poi API .Net Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Create Issue (Build)
      if: ${{ failure() }}
      uses: alialaa/issue-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "API - POI - Failed .NET Build"
        body: "The API failed to build branch: ${{ github.ref }} commit ID: ${{ github.sha }}"
        assignees: | 
          selleny
          hraffaele
          MSFTDELANEY
          JSandersMSFT

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Create Issue (Test)
      if: ${{ failure() }}
      uses: alialaa/issue-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "API - POI - Failed .NET Test"
        body: "The API failed to test branch: ${{ github.ref }} commit ID: ${{ github.sha }}"
        assignees: | 
          selleny
          hraffaele
          MSFTDELANEY
          JSandersMSFT
  job2:
    needs: job1
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
    name: CD - Deploy to ACR

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
      
    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
       login-server: openhackbxb3pxs9acr.azurecr.io
       username: ${{ secrets.REGISTRY_USERNAME }}
       password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        cd web
        docker build . -t openhackbxb3pxs9acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }} -t openhackbxb3pxs9acr.azurecr.io/devopsoh/api-poi:latest
        docker push openhackbxb3pxs9acr.azurecr.io/devopsoh/api-poi
  job3:
    needs: job2
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
    name: CD - Deploy to App Service Slot (Staging)
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: openhackbxb3pxs9acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackbxb3pxs9poi'
        slot-name: 'staging'
        images: 'openhackbxb3pxs9acr.azurecr.io/devopsoh/api-poi:latest'
    
    - name: Azure logout
      run: |
        az logout
        
