name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:    
    working-directory: apis/trips/

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Unit Tests
      run: go test
