name: Trips API CI-CD

on:
  push:
    paths: ['apis/trips/**']
  pull_request:
    branches: [ master ]

defaults:
  run:    
    working-directory: apis/trips/

jobs:
  job1:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Unit Tests
      run: go test ./tests

  job2:
    needs: job1
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
    name: CD - Deploy to ACR

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
      
    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
       login-server: openhackbxb3pxs9acr.azurecr.io
       username: ${{ secrets.REGISTRY_USERNAME }}
       password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t openhackbxb3pxs9acr.azurecr.io/devopsoh/api-trips:${{ github.run_id }} -t openhackbxb3pxs9acr.azurecr.io/devopsoh/api-trips:latest
        docker push openhackbxb3pxs9acr.azurecr.io/devopsoh/api-trips

  job3:
    needs: job2
    if: github.ref == 'refs/heads/master'
          
    runs-on: ubuntu-latest
    name: CD - Deploy to App Service Slot (Staging)
          
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
          
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - uses: azure/docker-login@v1
      with:
        login-server: openhackbxb3pxs9acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
            
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackbxb3pxs9trips'
        slot-name: 'staging'
        images: 'openhackbxb3pxs9acr.azurecr.io/devopsoh/api-trips:latest'
          
    - name: Azure logout
      run: |
        az logout
      