# This is a basic workflow to help you get started with Actions

name: Herb Test 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch 
on:
  push:
    branches: [ master ]

jobs:
  job1:
    name: GET
    runs-on: ubuntu-latest

    steps:            
        - uses: satak/webrequest-action@master
          name: webhook
          id: webhook
          with:
            url: https://openhackbxb3pxs9userjava.azurewebsites.net/api/healthcheck/user-java
            method: GET                        
        - run: |
            echo "${{fromJson(steps.webhook.outputs.output).data.status == 'healthy'}}"  
          
