# This is a basic workflow to help you get started with Actions

name: Herb Test 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch 
on:
  push:
    branches: [ master ]

jobs:
  job1:
    name: GET
    runs-on: ubuntu-latest

    steps:            
        - uses: satak/webrequest-action@master
          name: webhook
          with:
            url: https://openhackbxb3pxs9userjava.azurewebsites.net/api/healthcheck/user-java
            method: GET
        - run: |
            $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
            Write-Host "Output $($output.data.status)"


  job2:
    needs: job1
    name: READ    
    runs-on: ubuntu-latest
        
    steps:  
    - run: |
        cd web
        docker build . -t openhackbxb3pxs9acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }} -t openhackbxb3pxs9acr.azurecr.io/devopsoh/api-poi:latest
        docker push openhackbxb3pxs9acr.azurecr.io/devopsoh/api-poi


