# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: User-Java API Pipeline

on:
  push:
    branches: [ master ]
    paths: ['apis/user-java/**']
    
  pull_request:
    branches: [ master ]
    paths: ['apis/user-java/**']

defaults:
  run:    
    working-directory: apis/user-java/

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Maven Project

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Clean Maven Install
      run: mvn clean install
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Create Issue (Build)
      if: ${{ failure() }}
      uses: alialaa/issue-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "API - User-Java - Failed Maven Build"
        body: "The API failed to build"
        assignees: | 
          selleny
          MSFTDELANEY
          JSandersMSFT

    - name: Run Tests
      run: mvn test   

    - name: Create Issue (Test)
      if: ${{ failure() }}
      uses: alialaa/issue-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "API - User-Java - Failed Maven Test"
        body: "The API failed to test"
        assignees: | 
          selleny
          MSFTDELANEY
          JSandersMSFT