name: User Profile CI-CD

on:
  push:
    paths: ['apis/userprofile/**']
    
  pull_request:
    branches: [ master ]

defaults:
  run:    
    working-directory: apis/userprofile/

env:
  CI: true

jobs:
  job1:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project,
        npm install
        npm run build --if-present
        npm run test --if-present

  job2:
    needs: job1
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
    name: CD - Deploy to ACR

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
      
    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
       login-server: openhackbxb3pxs9acr.azurecr.io
       username: ${{ secrets.REGISTRY_USERNAME }}
       password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t openhackbxb3pxs9acr.azurecr.io/devopsoh/api-userprofile:${{ github.run_id }} -t openhackbxb3pxs9acr.azurecr.io/devopsoh/api-userprofile:latest
        docker push openhackbxb3pxs9acr.azurecr.io/devopsoh/api-userprofile

  job3:
    needs: job2
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
    name: CD - Deploy to App Service Slot (Staging)
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: openhackbxb3pxs9acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackbxb3pxs9userprofile'
        slot-name: 'staging'
        images: 'openhackbxb3pxs9acr.azurecr.io/devopsoh/api-userprofile:latest'
    
    - name: Azure logout
      run: |
        az logout